config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'reservations/update'
  get 'reservations/destroy'
  devise_for :admins
  get 'agendas/new'
  get 'agendas/show'
  get 'agendas/edit'
  get 'agendas/create'
  get 'agendas/destroy'
  get 'users/index'
  get 'users/update'
  get 'users/destroy'
  get 'shops/top'
  get 'shops/menu'
  get 'shops/access'
  get 'shops/note'
  get 'shops/reservation'
  get 'shops/new'
  get 'shops/edit'
  get 'user/index'
  get 'user/update'
  get 'user/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :menu
	has_many :reservations
end

app/models/menu.rb
class Menu < ApplicationRecord
	has_many :courses
	has_many :courses, through: :reservations
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :course
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end

  def create
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
  end

  def update
  end

  def destroy
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def top
  end

  def menu
  end

  def access
  end

  def note
  end

  def reservation
    @course = Course.new
    @reservation = Reservation.new
  end

  def new
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def update
  end

  def destroy
  end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/agendas/create.html.erb
<h1>Agendas#create</h1>
<p>Find me in app/views/agendas/create.html.erb</p>

app/views/agendas/destroy.html.erb
<h1>Agendas#destroy</h1>
<p>Find me in app/views/agendas/destroy.html.erb</p>

app/views/agendas/edit.html.erb
<h1>Agendas#edit</h1>
<p>Find me in app/views/agendas/edit.html.erb</p>

app/views/agendas/new.html.erb
<h1>Agendas#new</h1>
<p>Find me in app/views/agendas/new.html.erb</p>

app/views/agendas/show.html.erb
<h1>Agendas#show</h1>
<p>Find me in app/views/agendas/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ichi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

            <!-- 管理者ログイン時のヘッダー -->

        <% if admin_signed_in?  %>
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarEexample3">
                        <ul class="nav navbar-nav">
                            <%= link_to shops_top_path do %>
                                <img src="/3488_logo_dog_01.jpg" class="header-logo" style="float:left; height:7%; width:7%;">
                            <% end %>
                            <div style="float:right;">
                                <li class="text"><%= link_to "コース・料金", shops_menu_path %></li>
                                <li class="text"><%= link_to "注意事項", shops_note_path %></li>
                                <li class="text"><%= link_to "アクセス", shops_access_path %></li>
                                <li class="text"><%= link_to "予約状況・予約フォーム",  shops_reservation_path %></li>
                                <li class="text"><%=link_to "管理者ページ", reservations_index_path, "data-confirm" => "ログアウトしますか？", method: :delete %></li>
                                <li class="text"><%=link_to "ログアウト", destroy_admin_session_path, "data-confirm" => "ログアウトしますか？", method: :delete %></li>
                            </div>
                        </ul>
                    </div>
                </div>
            </nav>
        <% else %>

            <!-- 一般ユーザーのヘッダー -->

            <nav class="navbar navbar-default" style="display: flex;" >
              <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarEexample3">
                        <ul class="nav navbar-nav">
                            <%= link_to shops_top_path do %>
                                <img src="/3488_logo_dog_01.jpg" class="header-logo" style="float:left; height:7%; width:7%;">
                            <% end %>
                            <div style="float:right;">
                                <li class="text"><%= link_to "コース・料金", shops_menu_path %></li>
                                <li class="text"><%= link_to "注意事項", shops_note_path %></li>
                                <li class="text"><%= link_to "アクセス", shops_access_path %></li>
                                <li class="text"><%= link_to "予約状況・予約フォーム",  shops_reservation_path %></li>
                            </div>
                        </ul>
                    </div>
                </div>
            </nav>
        <% end %>

    </header>
    <%= yield %>
    <footer class="footer-color">
              <%=link_to "運営に質問する", "https://docs.google.com/forms/d/e/1FAIpQLSelvK_znRgNptqpfQkwrD-ev7FtCemK3y6qfIqXvynVoiOT9g/viewform", style:"color:black; margin-left: 70%; " %>
              <h5 style="color: black; margin-bottom: 0px; margin-left: 70%;">電話受付時間：9:30
              〜20:00</h5>
              <h5 style="color: black; margin-bottom: 0px; margin-top: 10px; margin-left: 70%;">お電話：03-6904-1073</h5>
              <h5 style="color: black; margin-bottom: 0px; margin-top: 10px; margin-left: 70%;">LINEID：ichi-1073</h5>
        </footer>
  </body>
</html>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/shops/access.html.erb
<h1>Shops#access</h1>
<p>Find me in app/views/shops/access.html.erb</p>

app/views/shops/edit.html.erb
<h1>Shops#edit</h1>
<p>Find me in app/views/shops/edit.html.erb</p>

app/views/shops/menu.html.erb
<h1>Shops#menu</h1>
<p>Find me in app/views/shops/menu.html.erb</p>

app/views/shops/new.html.erb
<h1>Shops#new</h1>
<p>Find me in app/views/shops/new.html.erb</p>

app/views/shops/note.html.erb
<h1>Shops#note</h1>
<p>Find me in app/views/shops/note.html.erb</p>

app/views/shops/reservation.html.erb
<h1>Shops#reservation</h1>
<p>Find me in app/views/shops/reservation.html.erb</p>

	<h1 class="text" style="margin:40px 0px;">予約する</h1>
		<%#= form_for @reservation do |f| %>
		<%= form_with(model: @reservation, local: false) do |f| %>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【予約者名】, class: "text" %><br />
			<%= f.text_field :user_name, autofocus: true, autocomplete: "user_name", placeholder:"漢字で名前を記入" %>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【予約者カナ名】, class: "text" %><br />
			<%= f.text_field :user_kana_name, autofocus: true, autocomplete: "user_kana_name", placeholder:"カタカナで名前を記入" %>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【性別】, class: "text" %><br />
				<%= f.select :gender, [["男性", "男性"], ["女性", "女性"]] %></br>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【メールアドレス】, class: "text" %><br />
			<%= f.text_field :user_email, autofocus: true, autocomplete: "uuser_email", placeholder:"メールアドレスは正確にご記入ください" %>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【電話番号】, class: "text" %><br />
			<%= f.number_field :user_phone_number, autofocus: true, autocomplete: "user_phone_number", placeholder:"半角数字で記入" %>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【ご希望のコース】, class: "text" %><br />
				<%= f.select :request_course, [["もみほぐし60分", "もみほぐし60分"], ["もみほぐし90分", "もみほぐし90分"], ["もみほぐし120分", "もみほぐし120分"], ["もみほぐし150分", "もみほぐし150分"], ["もみほぐし180分", "もみほぐし180分"]] %></br>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【開始時間】, class: "text" %><br />
			<%= f.select :start_time, [["10時", "10時"], ["11時", "11時"], ["12時", "12時"], ["13時", "13時"], ["14時", "14時"], ["15時", "15時"], ["16時", "16時"], ["17時", "17時"], ["18時", "18時"], ["19時", "19時"]] %>施術開始</br>
			</div>

			<div class="field text" style="margin-bottom: 20px; font-size: 30px;">
			<%= f.label :【要望】, class: "text" %><br />
			<%= f.text_area :demand, autofocus: true, placeholder:"要望があればお気軽にご記入ください" %>

			<div class="actions text" style="margin-bottom: 75px; font-size: 30px;">
			<%= f.submit "予約する", class: "btn btn-default text", style:"font-size:40px; padding:10px 30px; margin-top:20px;" %>
			</div>

		<% end %>

app/views/shops/top.html.erb
<h1>ichiについて</h1>
<h3>「一期一会」</h3>
<h4>～once-in-a-lifetime encounter～</h4>
<p>お客様にとっての、“No.1”、“Only1”になりたいという想いから、「ichi」と名付けました。</br>
出会いを大切に想い、今できる最高のおもてなしをお客様にご提供いたします。</br>
心、身体の疲れを癒し、慌ただしい日常とは違う空間で、心からリラックスしていただけるよう、</br>
お客様のニーズ、コンディションに合わせ、あなただけのオリジナルメニューをご提案いたします。</br>

お客様の本来の美しさを引き出し、お客様一人一人の魅力を最大限に引き出します。</br>
ご自身へのご褒美に、ゆったりとした時間をプライベートサロン「ichi」でお過ごしいただけたら嬉しいです。</p><br>
<h1>セラピスト紹介</h1>